spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/campus_management?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9090
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8

mybatis:
  type-aliases-package: com.demo.pojo
  mapperLocations: classpath:mybatis/mapper/*.xml

config:
  jwt:
    #加密秘钥
    secret: abcdefg1234567
    # token有效时长
    expire: 3600
    #header
    header: token
